import type { NextPage } from "next";
import Head from "next/head";
import Footer from "components/Footer";
import styles from "styles/Home.module.css";
import HeroBlock from "components/Blocks/HeroBlock";
import TestimonialBlock from "components/Blocks/TestimonialBlock";
import ArticlePromotionBlock from "components/Blocks/ArticlePromotionBlock";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Almers Agency</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HeroBlock />
        <ArticlePromotionBlock />
        <TestimonialBlock />
      </main>
    </div>
  );
};

export default Home;
